### ISSUE TITLE
why it's not working 

### ISSUE THREAD

**Issue by Mohamed3bdelwahab** [0v3rW4tch/uncompyle4all#1]
nice job bro but why it's not working  just  print 

0it [00:00, ?it/s]

[+] 2022-11-20-16-09.log ----> The log file is created!

that's  is everything  log is empty 

what should be the format  of file that decrypt  it
or how work .
i used this command    
python uncompyle4all.py -p enc.py -t 20

python uncompyle4all.py -p enc.py

**Comment by 0v3rW4tch** [comment]
> nice job bro but why it's not working just print
> 
> 0it [00:00, ?it/s]
> 
> [+] 2022-11-20-16-09.log ----> The log file is created!
> 
> that's is everything log is empty
> 
> what should be the format of file that decrypt it or how work . i used this command python uncompyle4all.py -p enc.py -t 20
> 
> python uncompyle4all.py -p enc.py

send me the enc.py file, I want to see what was wrong :)

**Comment by Mohamed3bdelwahab** [comment]
this is it

**Comment by Mohamed3bdelwahab** [comment]
[re1.zip](https://github.com/0v3rW4tch/uncompyle4all/files/10051926/re1.zip)

**Comment by 0v3rW4tch** [comment]
> [re1.zip](https://github.com/0v3rW4tch/uncompyle4all/files/10051926/re1.zip)
Your file is not a pyc file, so it will not work
